name: Get Latest Commit ID
on:
  push:
    branches:
      - Master

jobs:
  get_commit_id:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Latest Commit ID
        id: commit
        run: |
          echo "Latest Commit ID: ${{ github.sha }}"
